services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - "5000:8080"   # HTTP
      - "5001:8081"   # HTTPS
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=postgres;Database=ActivityDB;User=postgres;Password=1234qwer
      - Redis__ConnectionString=redis:6379
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ActivityDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234qwer
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
volumes:
  sql_data:
  redis_data: